/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed-dim": "#d0bcff",
              "on-secondary-fixed": "#00210c",
              "primary-fixed-dim": "#e2c288",
              "on-tertiary-container": "#4f07b9",
              "surface-bright": "#3a3939",
              "inverse-primary": "#735b2b",
              "glass-bg": "rgba(18, 18, 18, 0.7)",
              "on-tertiary": "#3c0091",
              "inverse-surface": "#e5e2e1",
              "on-tertiary-fixed-variant": "#5516be",
              "text-primary": "#F9FAFB",
              "on-surface-variant": "#d0c5b6",
              "secondary-fixed-dim": "#4de082",
              "on-primary-fixed-variant": "#594315",
              "primary-fixed": "#ffdea3",
              "on-surface": "#e5e2e1",
              "on-secondary-container": "#003e1c",
              "text-muted": "#9CA3AF",
              "on-tertiary-fixed": "#23005c",
              "error": "#ffb4ab",
              "outline-variant": "#4d463a",
              "on-background": "#e5e2e1",
              "on-primary": "#402d01",
              "tertiary-container": "#ba9eff",
              "on-error": "#690005",
              "tertiary": "#d3bfff",
              "on-error-container": "#ffdad6",
              "on-primary-container": "#533e10",
              "surface-container-highest": "#353534",
              "background": "#0A0A0A",
              "surface-dim": "#131313",
              "surface-tint": "#e2c288",
              "glass-border": "rgba(255, 255, 255, 0.12)",
              "secondary-container": "#00b55d",
              "secondary": "#4de082",
              "surface-container": "#201f1f",
              "surface-container-low": "#1c1b1b",
              "surface-container-lowest": "#0e0e0e",
              "tertiary-fixed": "#e9ddff",
              "surface-container-high": "#2a2a2a",
              "on-primary-fixed": "#261900",
              "on-secondary": "#003919",
              "surface-variant": "#353534",
              "primary": "#e5c58b",
              "outline": "#998f81",
              "primary-container": "#c8aa72",
              "inverse-on-surface": "#313030",
              "on-secondary-fixed-variant": "#005227",
              "error-container": "#93000a",
              "surface": "#131313",
              "secondary-fixed": "#6dfe9c"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "gutter": "24px",
              "margin-desktop": "80px",
              "unit": "4px",
              "section-gap": "120px",
              "margin-mobile": "20px"
      },
      "fontFamily": {
              "label-sm": ["JetBrains Mono", "monospace"],
              "body-lg": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "display-lg": ["Hanken Grotesk", "sans-serif"],
              "headline-sm": ["Hanken Grotesk", "sans-serif"],
              "headline-md": ["Hanken Grotesk", "sans-serif"],
              "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
              "label-md": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
}
